# Generated by Django 2.1.7 on 2019-03-10 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 10, 20, 6, 45, 487182), verbose_name='date published'),
        ),
    ]
