# Generated by Django 2.1.7 on 2019-03-29 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190320_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialcategory',
            name='image',
            field=models.ImageField(default='exit', upload_to='img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 29, 16, 1, 38, 947104), verbose_name='date published'),
        ),
    ]
